// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmanmddtrmfqsjqdvznm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtYW5tZGR0cm1mcXNqcWR2em5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzQ0NzAsImV4cCI6MjA3MzcxMDQ3MH0.fsP3yDQrm_nclHSsWoVX2MzIkzBeqW71Z8j8ioZh26Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});